### ISSUE TITLE
Missing base config file "./.svelte-kit/tsconfig.json"

### ISSUE THREAD

**Issue by tsekiguchi** [LukeHagar/sveltekit-adapters#6]
Hi!

I'm really interested in figuring out how to use SvelteKit within Electron, and your adapter looks really promising! In fact, it might be the only option out there right now. However, I'm trying to test out the examples to see how everything is built, but I'm getting the error then running "npm run build" that I'm missing ./svelte-kit/ts.config.json. In fact I'm missing the entire .svelte-kit folder, which I'm assuming is in the .gitignore. Any chance that you could help me solve this so I can check this package out?

Also on another note, I've been stuck in config hell for a couple days trying to figure out how to get sveltekit to work within electron. Is there an easy way that you already know of to get SK set up in electron-vite? I would be eternally grateful for your help!

Thank you!

**Comment by tsekiguchi** [comment]
Thank you so much for your help!!

After running `pnpm i` and `npm run dev` in sveltekit-adapters folder, the .svelte-kit folder still wasn't getting built, so I ended up copying from another project and placing in the electron and appwrite folder. That definitely fixed the first error, and got the appwrite example to properly display, but electron is still throwing some errors:

```
sveltekit-electron:dev: 
sveltekit-electron:dev:   ➜  Local:   http://localhost:5174/
sveltekit-electron:dev:   ➜  Network: use --host to expose
sveltekit-electron:dev: 
sveltekit-electron:dev: start electron app...
sveltekit-electron:dev: 
sveltekit-electron:dev: dyld[85357]: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
sveltekit-electron:dev:   Referenced from: <4C4C449D-5555-3144-A116-1EB4B114BBD5> /Users/timsekiguchi/sveltekit-adapters/node_modules/.pnpm/electron@28.2.3/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron
sveltekit-electron:dev:   Reason: tried: '/Users/timsekiguchi/sveltekit-adapters/node_modules/.pnpm/electron@28.2.3/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/Users/timsekiguchi/sveltekit-adapters/node_modules/.pnpm/electron@28.2.3/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' (no such file)
```

I'm currently stuck at getting sveltekit to read the `app.html` within the `src/renderer/src` path. I've thought that adjusting the `svelte.config` file according to the sveltekit documentation would get me there, but the change I made to point everything into the renderer folder doesn't seem to be applied. I have copied over everything that I designed in the lib and routes.

I've uploaded where I'm currently at here:
https://github.com/tsekiguchi/vite-electron-template

Let me know if there's anything that stands out to you or if I can explain anything! Thank you again in advance!

**Comment by tsekiguchi** [comment]
Howdy!

After some searching, I went back into the archives of issues in the original electron-vite github and found this solution!

https://github.com/alex8088/electron-vite/issues/145

Essentially, he disabled the renderer in electron.vite.config, brought sveltekit into the renderer, and then managed all building from within there, and then output to a directory for electron to get a hold of. I can't believe it took me this long to find this 

I don't know if this is similar to the template that you're building, but after bringing my existing project over into the template and updating a couple dependencies, everything is working smoothly.

Let me know if you ever need help with what you're doing! I'm fresh into development, and would love to get involved in some projects that I'm now finally understanding. 

Thank you again! 🙏

**Comment by Karechta** [comment]
I fixed the missing base config file error by running adding a script
`"svelte:dev": "vite dev"`
and running it to generate those files.
Once its generated it uses the file just fine and even updates it when ran with electron-vite.

**Comment by tsekiguchi** [comment]
Yes! Thank you for the clarification, I didn't realize at first when I was starting to use this that I needed to cd in to the renderer folder and run the dev script there in order for `.sveltekit` to populate itself.
